version: '3.9'

# TODO: mkcert ssl

services:
  webapi:
    restart: always
    container_name: webapi
    build: ./src/Weather.WebApi/
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<emulator-hostname>.pfx
      - Weather__KeyVaultUri=http://azure-keyvault-emulator:5000/

  azure-keyvault-emulator:
    container_name: azure-keyvault-emulator
    image: basis-theory/azure-keyvault-emulator:latest
    ports:
      - 5001:5001
      - 5000:5000
    volumes:
      - <path-to-certs>:/https
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<emulator-hostname>.pfx
      - KeyVault__Name=<emulator-hostname> 

  mssql:
    restart: always
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge # https://hub.docker.com/_/microsoft-azure-sql-edge
    environment:
      - SA_PASSWORD=topsecret!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_volume:/var/opt/mssql

volumes:
  db_volume: {}